import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MainHeader } from "components/MainHeader";
import { Navigation } from "components/Navigation";
import StyledComponentsRegistry from "lib/AntdRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={(inter.className, "overflow-x-hidden")}>
        <StyledComponentsRegistry>
          <div className="flex">
            <Navigation />
            <main className="w-full">
              <MainHeader />
              {children}
            </main>
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
