import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MainHeader } from "components/MainHeader";
import { SideNavigation } from "components/SideNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={(inter.className, "overflow-x-hidden")}>
        <div className="flex">
          <SideNavigation />
          <main className="w-full">
            <MainHeader />
            <div className="main-content p-2.5">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
